### PR TITLE
feat: handle parametrized generics

### PR DESCRIPTION
**Pull request by brisvag**
I added a lot of tests and slowly made my way trhough them; now almost everything works.

Main changes:
1. added two more validators that do the same as `validat_sequence_like`, but preserving type because they're followed up by the type coercing validator
2. forced into the `SHAPE_GENERIC` branch anything that should end up there and wasn't (all the parametrized sequence-like, mapping-like and so on), so we can use our own validators from point 1.

### CODE REVIEW

**Comment by tlambert03** [comment]
holy 💩!  very exciting  :)

**Comment by brisvag** [comment]
One thing is failing, confusingly: `Union` is coercing to whatever the first type in the union is, despite having seemingly *no* validators on the field...

**Comment by brisvag** [comment]
Also, 3.8 is apparently failing miserably because... typing changes?

**Comment by tlambert03** [comment]
> Also, 3.8 is apparently failing miserably because... typing changes?

what's even stranger there is that the exception is ultimately coming from `typing_extensions.py`  (which I _think_ we don't even directly use anywhere)

... so that might be coming from something that pydantic is doing with typing extensions

**Comment by brisvag** [comment]
I added tests with a subclass of `str`; these are a good example of some of the issues we had in napari when we created types just for the purpose of having validators, but we don't actually want the resulting object to be of a different type. In this case, we probably would like the type to *not* be coerced.

The solution I had in my original PR was to have an opt-out/opt-in mechanism... alternatives:
- do like normal pydantic, where if `__get_validators__` exists, no default validation happens. This however means that if we give any complex class validators to a `Sequence`, we won't get any element-wise validation for free, but instead we have to reimplement it.
- find some other trick to opt out that makes sense (make it into a protocol and ignore those?)
- bite the bullet and use the coerced types, which means sanitizing the values if we ever pass them to something fussy like `qt` or the `yaml dumper` (examples from the original napari issues).

**Comment by tlambert03** [comment]
ah right... yeah that's a useful feature https://pydantic-docs.helpmanual.io/usage/model_config/#smart-union

**Comment by tlambert03** [comment]
> these are a good example of some of the issues we had in napari when we created types just for the purpose of having validators, but we don't actually want the resulting object to be of a different type. In this case, we probably would like the type to not be coerced.

I actually think that the two main cases where that was done in napari `Theme(str)` and something else... are probably actually themselves not "correct" usages... and could have been better substituted by a Union of Literals, or provided a "pre/always" validator that checks against a set of strings.

so, if someone does:
```python
class MyStr(str):
    ...

class Model(BaseModel):
    s: MyStr
```

I absolutely think that `Model().s` should be an instance of MyStr

**Comment by brisvag** [comment]
> I actually think that the two main cases where that was done in napari `Theme(str)` and something else... are probably actually themselves not "correct" usages... and could have been better substituted by a Union of Literals, or provided a "pre/always" validator that checks against a set of strings.

I think I agree :+1:

**Review by tlambert03 — APPROVED** [review]
❤️

**Pull request merged**
